[package]
name = "btk-akademi-rust"
version = "0.1.0"
edition = "2021"
authors = ["Gokay BURUC", "Gokay Buruc <gokayburuc@yandex.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
